package com.example.demobcknd.services;

import com.example.demobcknd.models.theater;
import com.example.demobcknd.repositories.theaterRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class theaterService {
    @Autowired // This means to get the bean called userRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private theaterRepository theaterrepository;

    public Iterable<theater> findAllTheaters() {
        return theaterrepository.findAll();

    }

    public theater findTheater(int theaterId) {
        return theaterrepository.findById(theaterId).get();
    }

    public void addTheater(theater newTheater) {
        theaterrepository.save(newTheater);
    }

    public void deleteTheater(int theaterId) {
        theaterrepository.deleteById(theaterId);
    }

    public void updateTheater(int id, theater newTheater) {
        theater t = theaterrepository.findById(id).get();
        t.setAddress(newTheater.getAddress());
        t.setPostalCode(newTheater.getPostalCode());
        t.setPhone(newTheater.getPhone());
        t.setMail(newTheater.getMail());
        theaterrepository.save(t);
    }



}