package com.example.demobcknd.services;

import com.example.demobcknd.models.theater;
import com.example.demobcknd.repositories.theaterRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class theaterService {
    @Autowired // This means to get the bean called userRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private theaterRepository theaterrepository;

    public Iterable<theater> findAllTheaters() {
        return theaterrepository.findAll();

    }

    public theater findTheater(int id) {
        return theaterrepository.findById(id).get();
    }

    public String addTheater(String address, String postalcode, String phone, String mail) {
        theater t= new theater();
        t.setAddress(address);
        t.setPostalCode(postalcode);
        t.setPhone(phone);
        t.setMail(mail);
        theaterrepository.save(t);
        return "Saved";
    }

    public String deleteTheater(int id) {
        theaterrepository.deleteById(id);
        return "deleted";
    }

    public String updateTheater(int id, String address, String postalcode, String phone, String mail) {
        theater t = theaterrepository.findById(id).get();
        t.setAddress(address);
        t.setPostalCode(postalcode);
        t.setPhone(phone);
        t.setMail(mail);
        theaterrepository.save(t);
        return "updated";
    }

}