package com.example.demobcknd.services;

import com.example.demobcknd.models.user;
import com.example.demobcknd.repositories.userRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class userService {
    @Autowired // This means to get the bean called userRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private userRepository userRep;

    public Iterable<user> findAllUsers() {
        return userRep.findAll();
    }

    public user findUser(int id) {
        return userRep.findById(id).get();
    }

    public void addUser(user myuser) {
        userRep.save(myuser);
    }

    public String deleteUser(int id) {
        userRep.deleteById(id);
        return "deleted";
    }
    
    public String updateUser(int id, String email, String name) {
        user u = userRep.findById(id).get();
        u.setEmail(email);
        u.setName(name);
        userRep.save(u);
        return "updated";
    }

}